import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import test from 'node:test';

const source = readFileSync(new URL('../src/pages/Home/VisualCreationMode.jsx', import.meta.url), 'utf8');
const styles = readFileSync(new URL('../src/pages/Home/VisualCreationMode.css', import.meta.url), 'utf8');
const model = readFileSync(new URL('../src/pages/Home/visualCreationModel.js', import.meta.url), 'utf8');

test('visual creation is a complete conversation-style image workbench', () => {
  assert.match(source, /VISUAL_CREATION_SKILLS/);
  assert.match(source, /uploadEcommerceAssets/);
  assert.match(source, /regenerateCanvasImage/);
  assert.match(source, /includeMetadata:\s*true/);
  assert.match(source, /taskId:\s*result\.taskId/);
  assert.match(source, /generationUnits/);
  assert.match(source, /saveWork/);
  assert.match(source, /buildVisualCanvasResult/);
  assert.match(source, /JPG、PNG、WebP/);
  assert.match(source, /最多 6 张/);
  assert.match(source, /placeholder=\{`描述你想生成的/);
  assert.match(source, /只重试失败项/);
  assert.match(source, /进入画布/);
  assert.match(source, /下载/);
  assert.match(source, /creationIntent:\s*'visual'/);
  assert.match(source, /自由创作，做出可继续编辑的视觉/);
  assert.match(source, /VISUAL_SHOWCASE_AUTO_DWELL_MS/);
  assert.match(source, /VISUAL_SHOWCASE_MANUAL_DWELL_MS/);
  assert.match(source, /MentionPromptField/);
  assert.match(source, /insertMention/);
  assert.match(source, /visual-showcase-controls/);
  assert.match(source, /visual-skill-stage-card/);
  assert.match(source, /selectedSkill\.showcases/);
  assert.match(model, /productionCaseById/);
  assert.match(source, /visual-preview-dialog/);
  assert.match(source, /visual-skill-icon/);
  assert.match(source, /visual-ability-rail/);
  assert.match(source, /selectedSkill\.preserves/);
  assert.match(source, /selectedSkill\.outcome/);
  assert.match(source, /selectedSkill\.bestFor/);
  assert.match(source, /selectedShowcase\.outputs/);
  assert.doesNotMatch(source, /className="visual-skill-preview"/);
  assert.doesNotMatch(source, /className="visual-skill-facts"/);
  assert.doesNotMatch(source, /<b>保留<\/b>|<b>适合<\/b>|<b>结果<\/b>/);
  assert.match(styles, /\.visual-skill-grid/);
  assert.match(styles, /width:\s*min\(1240px,\s*100%\)/);
  assert.match(styles, /\.visual-skill-stage/);
  assert.match(styles, /padding:\s*clamp\(/);
  assert.match(styles, /\.visual-skill-stage-card/);
  assert.match(styles, /\.visual-showcase-controls/);
  assert.match(styles, /\.visual-ability-rail/);
  assert.match(styles, /\.visual-skill-option\.is-selected \.visual-skill-title strong/);
  assert.match(styles, /\.visual-creation-composer/);
  assert.doesNotMatch(styles, /width:\s*200%/);
  assert.doesNotMatch(styles, /margin-left:\s*-100%/);
  assert.match(styles, /@media \(max-width: 640px\)/);
  assert.match(styles, /@media \(prefers-reduced-motion: reduce\)/);
});
