/* 薯包AI · sample content for the UI kit (Xiaohongshu viral notes) */
window.SB_DATA = {
  gallery: [
    { id:1, cat:"旅游攻略", tone:"sun", grad:"var(--grad-sunset)", title:"反向旅游🔥这5个小县城比大理舒服100倍", likes:3852, cover:"mascot-surf",
      body:"谁懂啊！不去大理人挤人了，这5个小县城真的绝了\n📍 贵州黔东南·肇兴侗寨 人均300住3天\n📍 云南·芒市 东南亚风情满满的边境小城\n📍 福建·霞浦 摄影师天堂 日出美哭\n📍 浙江·松阳 最后的江南秘境\n📍 四川·西昌 邛海边的慢生活\n\n全部高铁可达周末就能出发\n物价感人100块吃一天不重样",
      tags:["反向旅游","小众旅行地","小县城","周末去哪儿","旅行攻略"] },
    { id:2, cat:"好物评测", tone:"coral", grad:"var(--grad-coral)", title:"拼多多30元以下好物🧧这8件真的物超所值", likes:2290, cover:"mascot-inspect",
      body:"PDD用了3年挖到的宝藏！全部30元以内\n🎯 手机支架 9.9元 追剧神器\n🎯 磁吸充电线 15元 再也不用插拔\n🎯 桌面收纳盒 12元 桌面瞬间整洁\n🎯 硅胶冰格 8元 夏天快乐水必备\n\n每个都亲自用过的不好用来骂我",
      tags:["拼多多好物","平价好物","学生党","省钱","居家好物"] },
    { id:3, cat:"美食探店", tone:"sun", grad:"var(--grad-sunset)", title:"社区咖啡店探店☕藏在小区里的神仙小店", likes:4523, cover:"mascot-cook",
      body:"小区楼下新开的咖啡店差点错过！\n☕ 招牌 Dirty 28元 一口惊艳\n🍰 巴斯克蛋糕 35元 不甜不腻刚刚好\n📸 每个角落都出片！胶片风装修\n📍 藏在老小区里导航到xx路再走3分钟",
      tags:["咖啡探店","社区咖啡","小众咖啡馆","上海美食","周末去哪"] },
    { id:4, cat:"穿搭分享", tone:"grape", grad:"var(--grad-grape)", title:"Clean Fit穿搭法则👔基础款也能穿出高级感", likes:5103, cover:"mascot-walk",
      body:"Clean Fit真的太适合普通人了！不用买大牌\n👕 上装：白T恤、条纹衫、衬衫选重磅面料\n👖 下装：直筒牛仔裤、卡其裤、阔腿西装裤\n👟 鞋子：德训鞋、帆布鞋、乐福鞋\n🎨 配色公式：黑白灰蓝卡其三色就够了",
      tags:["CleanFit","穿搭公式","基础款","极简穿搭","优衣库穿搭"] },
    { id:5, cat:"数码3C", tone:"grape", grad:"var(--grad-grape)", title:"2025年最值得买的AI工具合集🤖打工人必备", likes:3120, cover:"mascot-analyze",
      body:"用了半年AI工具这6个真的能提升效率\n🤖 写作翻译代码都强\n🎨 做设计太方便了\n📝 写周报会议纪要神器\n📊 做PPT只要5分钟\n\n每个我都深度用过的不是标题党",
      tags:["AI工具","效率神器","打工人","AIGC","干货"] },
    { id:6, cat:"学习干货", tone:"grape", grad:"var(--grad-grape)", title:"考研英语85分｜我做了这5件事上岸985📚", likes:6890, cover:"mascot-writing",
      body:"英语一85分！我的方法真的适合基础差的\n📌 单词：每天200个用艾宾浩斯记忆法\n📌 阅读：真题逐句分析\n📌 作文：整理5个万能模板+高级替换词\n📌 翻译：每天精翻2个长难句\n\n坚持4个月从四级飘到85分",
      tags:["考研英语","考研","上岸","985","学习经验"] },
    { id:7, cat:"家居家装", tone:"sprout", grad:"var(--grad-sprout)", title:"300元爆改出租屋🛏️房东看了想涨房租", likes:3421, cover:"mascot-paint",
      body:"月租800的老破小300块改造后不想出门了\n🛏️ 床头罩+靠枕 50元 遮丑效果绝了\n💡 日落灯+串灯 40元 氛围感拉满\n📦 收纳柜 80元 乱的东西全藏起来\n🪞 全身镜 60元 空间瞬间变大",
      tags:["出租屋改造","租房改造","老破小改造","独居","氛围感"] },
    { id:8, cat:"健身减肥", tone:"sprout", grad:"var(--grad-sprout)", title:"居家普拉提30天变化🔥肚子小了腰围瘦了8cm", likes:7340, cover:"mascot-lift",
      body:"坚持30天居家普拉提真的会谢！\n📌 Week1：每天10分钟基础核心训练\n📌 Week2：15分钟腹部+臀部专项\n📌 Week3：20分钟全身燃脂\n✅ 腰围从72到64cm\n✅ 体态肉眼可见变好",
      tags:["普拉提","居家健身","瘦腰","减肥","体态矫正"] },
  ],
  pricing: [
    { name:"入门", price:18, sets:6, regen:3, desc:"适合偶尔创作", per:"3.0" },
    { name:"进阶", price:42, sets:16, regen:5, pop:true, desc:"个人博主首选", per:"2.6" },
    { name:"创作者", price:78, sets:36, regen:8, desc:"高频创作者", per:"2.2" },
    { name:"工作室", price:148, sets:80, regen:"不限", desc:"团队批量使用", per:"1.85" },
  ],
  hints: ["反向旅游5个小县城","拼多多30元好物","小区宝藏咖啡店","Clean Fit基础穿搭","2025AI工具合集","考研英语85分方法","300元出租屋改造","精简护肤5样就够了"],
  tips: ["标题带数字的笔记，点击率平均高出 47%","发布时间建议：周四 / 周五晚上 8-9 点","正文前 3 行决定 80% 用户是否继续阅读","每篇笔记建议 5-7 个精准标签","封面配色统一度直接影响账号调性"],
  stages: [
    { pose:"analyze", label:"研读素材", desc:"小薯包正在认真分析你的内容…" },
    { pose:"writing", label:"撰写文案", desc:"灵感爆发！正在打磨爆款文案" },
    { pose:"paint", label:"生成配图", desc:"正在精心绘制 9 张图片" },
    { pose:"inspect", label:"质量检查", desc:"最后检查一下，确保每张都完美" },
    { pose:"done", label:"打包完成", desc:"搞定！你的爆款图文来啦" },
  ],
};
